# Generated by Django 2.2.6 on 2019-10-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
