# Generated by Django 2.2.6 on 2019-10-20 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapi', '0002_website_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ('id_web',)},
        ),
        migrations.CreateModel(
            name='linkapi',
            fields=[
                ('id_link', models.AutoField(primary_key=True, serialize=False)),
                ('urlapi', models.CharField(max_length=250)),
                ('deksripsi_link', models.TextField()),
                ('date_create', models.DateField(auto_now=True)),
                ('link_web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.website')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
